// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using System;
using ClientApi;
using Newtonsoft.Json.Linq;
using SpacetimeDB;

namespace SpacetimeDB.Types
{
	public static partial class Reducer
	{
		public delegate void MoveBulletsHandler(ReducerEvent reducerEvent, ulong prevTime);
		public static event MoveBulletsHandler OnMoveBulletsEvent;

		public static void MoveBullets(ulong prevTime)
		{
			var _argArray = new object[] {prevTime};
			var _message = new SpacetimeDBClient.ReducerCallRequest {
				fn = "move_bullets",
				args = _argArray,
			};
			Newtonsoft.Json.JsonSerializerSettings _settings = new Newtonsoft.Json.JsonSerializerSettings
			{
				Converters = { new SpacetimeDB.SomeWrapperConverter(), new SpacetimeDB.EnumWrapperConverter() },
				ContractResolver = new SpacetimeDB.JsonContractResolver(),
			};
			SpacetimeDBClient.instance.InternalCallReducer(Newtonsoft.Json.JsonConvert.SerializeObject(_message, _settings));
		}

		[ReducerCallback(FunctionName = "move_bullets")]
		public static bool OnMoveBullets(ClientApi.Event dbEvent)
		{
			if(OnMoveBulletsEvent != null)
			{
				var args = ((ReducerEvent)dbEvent.FunctionCall.CallInfo).MoveBulletsArgs;
				OnMoveBulletsEvent((ReducerEvent)dbEvent.FunctionCall.CallInfo
					,(ulong)args.PrevTime
				);
				return true;
			}
			return false;
		}

		[DeserializeEvent(FunctionName = "move_bullets")]
		public static void MoveBulletsDeserializeEventArgs(ClientApi.Event dbEvent)
		{
			var args = new MoveBulletsArgsStruct();
			var bsatnBytes = dbEvent.FunctionCall.ArgBytes;
			using var ms = new System.IO.MemoryStream();
			ms.SetLength(bsatnBytes.Length);
			bsatnBytes.CopyTo(ms.GetBuffer(), 0);
			ms.Position = 0;
			using var reader = new System.IO.BinaryReader(ms);
			var args_0_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U64), reader);
			args.PrevTime = args_0_value.AsU64();
			dbEvent.FunctionCall.CallInfo = new ReducerEvent(ReducerType.MoveBullets, "move_bullets", dbEvent.Timestamp, Identity.From(dbEvent.CallerIdentity.ToByteArray()), dbEvent.Message, dbEvent.Status, args);
		}
	}

	public partial class MoveBulletsArgsStruct
	{
		public ulong PrevTime;
	}

}
