// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using System;
using ClientApi;
using Newtonsoft.Json.Linq;
using SpacetimeDB;

namespace SpacetimeDB.Types
{
	public static partial class Reducer
	{
		public delegate void ShootBulletHandler(ReducerEvent reducerEvent, SpacetimeDB.Types.StdbVector2 location, SpacetimeDB.Types.StdbVector2 direction);
		public static event ShootBulletHandler OnShootBulletEvent;

		public static void ShootBullet(SpacetimeDB.Types.StdbVector2 location, SpacetimeDB.Types.StdbVector2 direction)
		{
			var _argArray = new object[] {location, direction};
			var _message = new SpacetimeDBClient.ReducerCallRequest {
				fn = "shoot_bullet",
				args = _argArray,
			};
			Newtonsoft.Json.JsonSerializerSettings _settings = new Newtonsoft.Json.JsonSerializerSettings
			{
				Converters = { new SpacetimeDB.SomeWrapperConverter(), new SpacetimeDB.EnumWrapperConverter() },
				ContractResolver = new SpacetimeDB.JsonContractResolver(),
			};
			SpacetimeDBClient.instance.InternalCallReducer(Newtonsoft.Json.JsonConvert.SerializeObject(_message, _settings));
		}

		[ReducerCallback(FunctionName = "shoot_bullet")]
		public static bool OnShootBullet(ClientApi.Event dbEvent)
		{
			if(OnShootBulletEvent != null)
			{
				var args = ((ReducerEvent)dbEvent.FunctionCall.CallInfo).ShootBulletArgs;
				OnShootBulletEvent((ReducerEvent)dbEvent.FunctionCall.CallInfo
					,(SpacetimeDB.Types.StdbVector2)args.Location
					,(SpacetimeDB.Types.StdbVector2)args.Direction
				);
				return true;
			}
			return false;
		}

		[DeserializeEvent(FunctionName = "shoot_bullet")]
		public static void ShootBulletDeserializeEventArgs(ClientApi.Event dbEvent)
		{
			var args = new ShootBulletArgsStruct();
			var bsatnBytes = dbEvent.FunctionCall.ArgBytes;
			using var ms = new System.IO.MemoryStream();
			ms.SetLength(bsatnBytes.Length);
			bsatnBytes.CopyTo(ms.GetBuffer(), 0);
			ms.Position = 0;
			using var reader = new System.IO.BinaryReader(ms);
			var args_0_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.Types.StdbVector2.GetAlgebraicType(), reader);
			args.Location = (SpacetimeDB.Types.StdbVector2)(args_0_value);
			var args_1_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.Types.StdbVector2.GetAlgebraicType(), reader);
			args.Direction = (SpacetimeDB.Types.StdbVector2)(args_1_value);
			dbEvent.FunctionCall.CallInfo = new ReducerEvent(ReducerType.ShootBullet, "shoot_bullet", dbEvent.Timestamp, Identity.From(dbEvent.CallerIdentity.ToByteArray()), dbEvent.Message, dbEvent.Status, args);
		}
	}

	public partial class ShootBulletArgsStruct
	{
		public SpacetimeDB.Types.StdbVector2 Location;
		public SpacetimeDB.Types.StdbVector2 Direction;
	}

}
